[package]
name = "uauauiua"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
crossterm = "0.28.1"
ecow = "0.2.3"
notify = "7.0.0"
ratatui = "0.29.0"
regex = "1.11.1"
rodio = "0.20.1"
tokio = { version = "1.43.0", features = ["sync"] }
uiua = {version = "0.14.1", default-features = false, features = ["native_sys"]}
