 // This file has been generated by Specta. DO NOT EDIT.

export type AudioData = { stackWav: number[]; varWavs: { [key in string]: number[] } }

export type TauRpcApiInputTypes = { proc_name: "format_code"; input_type: { __taurpc_type: string } } | { proc_name: "run_code"; input_type: { __taurpc_type: string } } | { proc_name: "sample_rate"; input_type: null }

export type TauRpcApiOutputTypes = { proc_name: "format_code"; output_type: string } | { proc_name: "run_code"; output_type: AudioData } | { proc_name: "sample_rate"; output_type: number }

const ARGS_MAP = {"":"{\"sample_rate\":[],\"format_code\":[\"code\"],\"run_code\":[\"code\"]}"}
import { createTauRPCProxy as createProxy } from "taurpc"

export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)

type Router = {
	'': [TauRpcApiInputTypes, TauRpcApiOutputTypes],
}