 // This file has been generated by Specta. DO NOT EDIT.

export type AudioData = { stackClips: Clip[]; varClips: { [key in string]: Clip } }

export type Clip = { wav: number[]; peaks: number[][] }

export type TauRpcApiInputTypes = { proc_name: "file_loaded"; input_type: { __taurpc_type: AudioData } } | { proc_name: "error"; input_type: { __taurpc_type: string } }

export type TauRpcApiOutputTypes = { proc_name: "file_loaded"; output_type: null } | { proc_name: "error"; output_type: null }

const ARGS_MAP = {"":"{\"error\":[\"error\"],\"file_loaded\":[\"clips\"]}"}
import { createTauRPCProxy as createProxy } from "taurpc"

export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)

type Router = {
	'': [TauRpcApiInputTypes, TauRpcApiOutputTypes],
}