 // This file has been generated by Specta. DO NOT EDIT.

export type TauRpcApiInputTypes = { proc_name: "format_code"; input_type: { __taurpc_type: string } } | { proc_name: "run_code"; input_type: { __taurpc_type: string } } | { proc_name: "var_samples"; input_type: null } | { proc_name: "load_stack_sample"; input_type: null } | { proc_name: "load_var_sample"; input_type: { __taurpc_type: string } } | { proc_name: "play"; input_type: null }

export type TauRpcApiOutputTypes = { proc_name: "format_code"; output_type: string } | { proc_name: "run_code"; output_type: null } | { proc_name: "var_samples"; output_type: { [key in string]: number[] } } | { proc_name: "load_stack_sample"; output_type: null } | { proc_name: "load_var_sample"; output_type: null } | { proc_name: "play"; output_type: null }

const ARGS_MAP = {"":"{\"load_var_sample\":[\"var\"],\"run_code\":[\"code\"],\"var_samples\":[],\"format_code\":[\"code\"],\"load_stack_sample\":[],\"play\":[]}"}
import { createTauRPCProxy as createProxy } from "taurpc"

export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)

type Router = {
	'': [TauRpcApiInputTypes, TauRpcApiOutputTypes],
}